### ISSUE TITLE
Metadata for liquidity tokens

### ISSUE THREAD

**Issue by Wiezzel** [paritytech/substrate-dex#15]

**Comment by Moliholy** [comment]
The extended version of ERC20 tokens includes three extra parameters to be included as metadata. See [here](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/IERC20Metadata.sol).

Is the main idea of this issue to include exactly those three to closely follow the standard?

**Comment by stiiifff** [comment]
@Moliholy IIRC the idea was to use the Asset pallet `set_metadata` extrinsic (via the [fungibles::metadata::Mutate trait](https://github.com/paritytech/substrate/blob/950628975e0c51e32055f9093bb091fb76a739d4/frame/support/src/traits/tokens/fungibles/metadata.rs#L32)).

**Comment by Moliholy** [comment]
...which adds those three extra parameters I mentioned. Alright, working on a PR 👍
