### ISSUE TITLE
Oracle use case.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/substrate-dex#24]
Is not strictly an XCM case, but i wonder if it would be interesting to implement a toy parachain with an oracle in it and make this pallet from Trappist read prices from this Oracle parachain.

What do you think @stiiifff @Wiezzel ?

P.S: I'm not creating this issue on Trappist since is a very raw idea that i want mostly Steve to confirm if it makes sense or not.

**Comment by Wiezzel** [comment]
What trading pairs would be included in this Oracle? And how would the prices be determined?

**Comment by bidzyyys** [comment]
@hbulgarini 's idea can be done with off-chain workers - it is possible with HTTP calls. I've seen OCWs in a list of feature proposals, so maybe it can be considered.

**Comment by stiiifff** [comment]
I think this is out of the scope of this pallet. Uniswap V1 is based on a constant-product formula and thus does not need a price feed oracle. See https://docs.uniswap.org/protocol/V1/introduction.
